In [7]:
'''
CIS-660 Lab 3 Assignment
Author: Mohamed Gani Mohamed Sulthan
CSU ID: 2811619
Major: Master’s in computer science
Credits: https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_knn_algorithm_finding_nearest_neighbors.htm, 
            https://www.kdnuggets.com/2020/01/decision-tree-algorithm-explained.html
'''
# Import all the required modules
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np
from scipy import spatial
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [8]:
# reading csv file
dataFrame = pd.read_csv(r"C:\Users\Gani\Downloads\vTargetBuyers.csv")

In [9]:
# Binarization
df_gender = pd.get_dummies(dataFrame["Gender"])
dataFrame['Gender'] = df_gender.cumsum(axis=1).ne(1).sum(axis=1)

# Converting Binarization
dataFrame['NumberCarsOwned'] = dataFrame['NumberCarsOwned'].apply(lambda x: 1 if x>=1 else 0)
dataFrame['TotalChildren'] = dataFrame['TotalChildren'].apply(lambda x: 1 if x>=1 else 0)
dataFrame['NumberChildrenAtHome'] = dataFrame['NumberChildrenAtHome'].apply(lambda x: 1 if x>=1 else 0)


# One hot Encoding
df_englishEducation = pd.get_dummies(dataFrame["EnglishEducation"])
dataFrame['EnglishEducation'] = df_englishEducation.cumsum(axis=1).ne(1).sum(axis=1)
df_englishOccupation = pd.get_dummies(dataFrame["EnglishOccupation"])
dataFrame['EnglishOccupation'] = df_englishOccupation.cumsum(axis=1).ne(1).sum(axis=1)
df_commuteDistance = pd.get_dummies(dataFrame["CommuteDistance"])
dataFrame['CommuteDistance'] = df_commuteDistance.cumsum(axis=1).ne(1).sum(axis=1)
df_region = pd.get_dummies(dataFrame["Region"])
dataFrame['Region'] = df_region.cumsum(axis=1).ne(1).sum(axis=1)

# Normalization
dataFrame['YearlyIncome'] = (dataFrame['YearlyIncome'] - dataFrame['YearlyIncome'].min()) / (dataFrame['YearlyIncome'].max() - dataFrame['YearlyIncome'].min())    
dataFrame['Age'] = (dataFrame['Age'] - dataFrame['Age'].min()) / (dataFrame['Age'].max() - dataFrame['Age'].min())   

In [10]:
dfa = dataFrame.drop('GeographyKey', axis=1)
display(dataFrame)

GeographyKey  Gender  YearlyIncome  TotalChildren  \
0                26       1        0.5000              1   
1                37       1        0.3125              1   
2                31       1        0.3125              1   
3                11       0        0.3750              0   
4                19       0        0.4375              1   
...             ...     ...           ...            ...   
18479           209       1        0.1250              1   
18480           248       0        0.1250              1   
18481           120       1        0.1250              1   
18482           179       1        0.1250              1   
18483           217       1        0.1250              0   

       NumberChildrenAtHome  EnglishEducation  EnglishOccupation  \
0                         0                 0                  3   
1                         1                 0                  3   
2                         1                 0                  3   
3                         0                 0                  3   
4                         1                 0                  3   
...                     ...               ...                ...   
18479                     0                 1                  0   
18480                     0                 1                  0   
18481                     0                 1                  0   
18482                     0                 0                  0   
18483                     0                 0                  0   

       HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region       Age  \
0                   1                0                1       2  0.211268   
1                   0                1                0       2  0.225352   
2                   1                1                3       2  0.225352   
3                   0                1                4       2  0.183099   
4                   1                1                1       2  0.183099   
...               ...              ...              ...     ...       ...   
18479               1                0                0       0  0.323944   
18480               1                0                0       0  0.281690   
18481               0                0                0       0  0.295775   
18482               1                0                0       0  0.309859   
18483               1                0                0       0  0.295775   

       BikeBuyer  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
18479          1  
18480          1  
18481          1  
18482          1  
18483          1  

[18484 rows x 13 columns]

In [21]:
# KNN Implementation
X = dfa.iloc[:, :-1].values
y = dfa.iloc[:, 11].values

#Splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

# Scaling
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# K N Classifier
classifier = KNeighborsClassifier(n_neighbors = 10)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Final
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("\nClassification Report:")
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("KNN Accuracy:",result2)

Confusion Matrix:
[[2896  849]
 [1189 2460]]

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.77      0.74      3745
           1       0.74      0.67      0.71      3649

    accuracy                           0.72      7394
   macro avg       0.73      0.72      0.72      7394
weighted avg       0.73      0.72      0.72      7394

KNN Accuracy: 0.724371111712199


In [25]:
# Decision tree implementation
X = dfa.iloc[:, :-1].values
y = dfa.iloc[:, 11].values

X_train, X_test, y_train, y_test =  train_test_split(X,y,test_size = 0.40, random_state= 0)

#feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Classifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train,y_train)

#prediction
y_pred = classifier.predict(X_test)#Accuracy
print(y_test)
print(y_pred)
 
from sklearn.metrics import accuracy_score #works
print('Decision Tree Accuracy:',accuracy_score(y_test, y_pred))

[1 1 0 ... 0 0 0]
[1 1 1 ... 0 0 0]
Decision Tree Accuracy: 0.738571814985123
